### ISSUE TITLE
How to configure varnish so that drupal can talk to it

### ISSUE THREAD

**Issue by phuang07** [docksal/service-varnish#5]
I think what i can trying to figure out is how to configure varnish so that the varnishd command will also take in:
1. secret key config
2. -T 0.0.0.0:6082

Currently I am using the 'varnish' module in drupal, but getting a message saying:
'The Varnish control terminal is not responding at 127.0.0.1 on port 6082', according to https://www.drupal.org/project/varnish/issues/1186842, I need to enable the '-T' flag. 

I also notice this varnish image only have port 80 open, is there anyway i can open up port 6082 as well?

Thanks in advance.

**Comment by lmakarov** [comment]
Try this:

```
# Varnish
varnish:
  hostname: varnish
  image: ${VARNISH_IMAGE:-docksal/varnish:1.0-varnish4}
  labels:
    - io.docksal.virtual-host=varnish.${VIRTUAL_HOST}
  expose:
    - "6082"
  environment:
    - VARNISH_BACKEND_HOST=web
    - VARNISH_VARNISHD_PARAMS="-T 0.0.0.0:6082"
```

**Comment by phuang07** [comment]
Hi @lmakarov,

Tried it. The expose port seems working great.
But adding '- VARNISH_VARNISHD_PARAMS="-T 0.0.0.0:6082"' causing the varnish container Exits immediately. Any thought on this?

Thanks.

**Comment by lmakarov** [comment]
@leoman730 this works:

```yaml
# Varnish
varnish:
  hostname: varnish
  image: ${VARNISH_IMAGE:-docksal/varnish:1.0-varnish4}
  labels:
    - io.docksal.virtual-host=varnish.${VIRTUAL_HOST}
  expose:
    - "6082"
  environment:
    - VARNISH_BACKEND_HOST=web
    - VARNISH_VARNISHD_PARAMS=-T :6082
```

Also, I'm going to include these update in the image, so there will be no need to set them as overrides in yml.
